import numpy as np
import pandas as pd
import scipy as sp

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/mobile/train.csv')

In [3]:
df.shape

(2000, 21)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   battery_power  2000 non-null   int64
 1   blue           2000 non-null   int64
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64
 4   fc             2000 non-null   int64
 5   four_g         2000 non-null   int64
 6   int_memory     2000 non-null   int64
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64
 9   n_cores        2000 non-null   int64
 10  pc             2000 non-null   int64
 11  px_height      2000 non-null   int64
 12  px_width       2000 non-null   int64
 13  ram            2000 non-null   int64
 14  sc_h           2000 non-null   int64
 15  sc_w           2000 non-null   int64
 16  talk_time      2000 non-null   int64
 17  three_g        2000 non-null   int64
 18  touch_screen   2000 non-null   int64
 19  wifi           2000 non-null   int64
 20  price_range    2000 non-null   int64
dtypes: float64(2), int64(19)
memory usage: 328.2 KB

In [6]:
df[['price_range']].head()

   price_range
0            1
1            2
2            2
3            2
4            1

### Q1

In [48]:
df.groupby(['price_range', 'n_cores']).size().sort_values().groupby(level=0).tail(1)

price_range  n_cores
0            2          69
3            5          70
2            4          73
1            1          76
dtype: int64

In [47]:
df.groupby(['price_range'])['n_cores'].value_counts().sort_values().groupby(level=0).tail(1)

price_range  n_cores
0            2          69
3            5          70
2            4          73
1            1          76
Name: n_cores, dtype: int64

### Q2

In [64]:
df[df['price_range']==3].corr()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
battery_power,1.000000,-0.019588,-0.047833,-0.134352,0.083515,0.014355,-0.041099,0.033896,-0.002937,-0.066908,...,-0.082547,-0.065939,-0.262759,-0.080752,-0.009713,0.086021,-0.020736,-0.033993,0.001345,NaN
blue,-0.019588,1.000000,0.074535,0.061992,0.031587,0.044653,-0.003080,-0.016718,-0.030398,-0.045381,...,0.043505,-0.066695,0.010000,0.001807,0.065277,-0.072417,-0.032623,0.060329,0.010291,NaN
clock_speed,-0.047833,0.074535,1.000000,-0.042840,0.095757,-0.144051,-0.008301,-0.075859,0.036738,-0.052820,...,0.046343,-0.011819,0.041331,0.047115,0.039579,-0.055842,-0.127549,0.010260,0.005814,NaN
dual_sim,-0.134352,0.061992,-0.042840,1.000000,-0.075681,-0.014096,-0.036384,-0.056753,-0.050991,-0.078633,...,-0.074033,-0.011231,0.094004,-0.067544,-0.041602,-0.078093,-0.076653,0.012503,-0.014924,NaN
fc,0.083515,0.031587,0.095757,-0.075681,1.000000,-0.053781,-0.039115,-0.042970,0.064398,-0.047587,...,0.044692,-0.025624,-0.050382,0.016927,0.024985,-0.029785,-0.031470,0.067129,0.010370,NaN
four_g,0.014355,0.044653,-0.144051,-0.014096,-0.053781,1.000000,-0.000090,0.098571,0.038960,0.061228,...,-0.024102,0.002240,-0.006090,0.007722,0.059551,-0.056890,0.604218,0.069149,0.015294,NaN
int_memory,-0.041099,-0.003080,-0.008301,-0.036384,-0.039115,-0.000090,1.000000,0.011611,-0.057593,-0.033523,...,-0.008610,0.035620,-0.048515,0.070163,0.005320,-0.020160,-0.016917,0.060954,0.025998,NaN
m_dep,0.033896,-0.016718,-0.075859,-0.056753,-0.042970,0.098571,0.011611,1.000000,0.015905,0.005673,...,-0.035808,-0.042339,-0.017574,-0.036196,-0.077183,0.037715,0.081976,0.037092,0.001044,NaN
mobile_wt,-0.002937,-0.030398,0.036738,-0.050991,0.064398,0.038960,-0.057593,0.015905,1.000000,-0.041840,...,-0.003764,-0.004345,0.107730,0.010026,-0.013806,-0.013653,0.034039,0.010625,0.055018,NaN
n_cores,-0.066908,-0.045381,-0.052820,-0.078633,-0.047587,0.061228,-0.033523,0.005673,-0.041840,1.000000,...,0.038382,0.124608,-0.036159,-0.032997,-0.011491,0.029556,0.013938,0.000879,0.006066,NaN
pc,0.025482,0.024459,0.052912,-0.051248,0.635166,-0.059680,-0.046525,0.024424,0.046314,-0.002674,...,0.000874,-0.050998,-0.015646,0.004423,-0.096039,0.010506,0.002541,0.042637,0.034056,NaN
px_height,-0.082547,0.043505,0.046343,-0.074033,0.044692,-0.024102,-0.008610,-0.035808,-0.003764,0.038382,...,1.000000,0.538207,-0.238720,0.117225,0.048856,0.021954,-0.056407,-0.042087,0.081369,NaN
px_width,-0.065939,-0.066695,-0.011819,-0.011231,-0.025624,0.002240,0.035620,-0.042339,-0.004345,0.124608,...,0.538207,1.000000,-0.257496,0.079685,0.016369,0.027057,-0.029298,0.018708,0.078801,NaN
ram,-0.262759,0.010000,0.041331,0.094004,-0.050382,-0.006090,-0.048515,-0.017574,0.107730,-0.036159,...,-0.238720,-0.257496,1.000000,0.005199,0.011657,-0.045694,0.016857,-0.000097,0.016474,NaN
sc_h,-0.080752,0.001807,0.047115,-0.067544,0.016927,0.007722,0.070163,-0.036196,0.010026,-0.032997,...,0.117225,0.079685,0.005199,1.000000,0.514600,0.008626,-0.005477,0.058934,0.038308,NaN
sc_w,-0.009713,0.065277,0.039579,-0.041602,0.024985,0.059551,0.005320,-0.077183,-0.013806,-0.011491,...,0.048856,0.016369,0.011657,0.514600,1.000000,-0.088692,0.025941,0.046907,0.018241,NaN
talk_time,0.086021,-0.072417,-0.055842,-0.078093,-0.029785,-0.056890,-0.020160,0.037715,-0.013653,0.029556,...,0.021954,0.027057,-0.045694,0.008626,-0.088692,1.000000,-0.076675,0.027730,-0.029220,NaN
three_g,-0.020736,-0.032623,-0.127549,-0.076653,-0.031470,0.604218,-0.016917,0.081976,0.034039,0.013938,...,-0.056407,-0.029298,0.016857,-0.005477,0.025941,-0.076675,1.000000,0.047907,-0.026074,NaN
touch_screen,-0.033993,0.060329,0.010260,0.012503,0.067129,0.069149,0.060954,0.037092,0.010625,0.000879,...,-0.042087,0.018708,-0.000097,0.058934,0.046907,0.027730,0.047907,1.000000,0.072470,NaN
wifi,0.001345,0.010291,0.005814,-0.014924,0.010370,0.015294,0.025998,0.001044,0.055018,0.006066,...,0.081369,0.078801,0.016474,0.038308,0.018241,-0.029220,-0.026074,0.072470,1.000000,NaN
price_range,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [125]:
data = df[df['price_range']==3].corr().unstack()
data.index.names = ['cate_1','cate_2']
data.name = 'value'

In [132]:
pd.DataFrame(data).reset_index().sort_values(['value'], ascending=False)

            cate_1         cate_2  value
0    battery_power  battery_power    1.0
220             pc             pc    1.0
66        dual_sim       dual_sim    1.0
88              fc             fc    1.0
110         four_g         four_g    1.0
..             ...            ...    ...
436    price_range      talk_time    NaN
437    price_range        three_g    NaN
438    price_range   touch_screen    NaN
439    price_range           wifi    NaN
440    price_range    price_range    NaN

[441 rows x 3 columns]

In [36]:
df1 = df[df['price_range']==3].corr().unstack().sort_values(ascending=False)

In [39]:
df2 = df1.loc[df1 != 1]

In [45]:
df2[1]

0.635165983662283